# Generated by Django 2.2 on 2021-02-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OCR', models.ImageField(upload_to='', verbose_name='img')),
            ],
        ),
    ]
